name: Setup Ollama
description: Install Ollama binary and restore model cache (tests pull models idempotently)

runs:
  using: composite
  steps:
    - name: Cache Ollama binary
      id: cache-ollama-binary
      uses: actions/cache@v4
      with:
        path: ./.ollama-install
        key: ${{ runner.os }}-ollama-binary-v2

    - name: Cache Ollama models
      id: cache-ollama-models
      uses: actions/cache@v4
      with:
        path: ~/.ollama
        key: ${{ runner.os }}-ollama-models-v2

    - name: Install Ollama binary (cache miss)
      if: steps.cache-ollama-binary.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Downloading Ollama binary..."
        ARCH=$(uname -m)
        case "$ARCH" in
            x86_64) ARCH="amd64" ;;
            aarch64|arm64) ARCH="arm64" ;;
            *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
        esac
        curl -L https://ollama.com/download/ollama-linux-${ARCH}.tgz -o ollama.tgz
        mkdir -p .ollama-install
        tar -C .ollama-install -xzf ollama.tgz
        rm ollama.tgz
        echo "Ollama binary downloaded"

    - name: Add Ollama to PATH
      shell: bash
      run: |
        echo "$(pwd)/.ollama-install/bin" >> $GITHUB_PATH

    - name: Start Ollama server
      shell: bash
      run: |
        echo "Starting Ollama server..."
        ollama start &
        sleep 2
        echo "Ollama server started"

    - name: Verify Ollama
      shell: bash
      run: |
        ollama --version
        echo "Ollama binary ready - tests will pull models idempotently"

    - name: Verify cache status
      shell: bash
      run: |
        if [[ "${STEPS_CACHE_OLLAMA_MODELS_OUTPUTS_CACHE_HIT}" == "true" ]]; then
          echo "Model cache restored - available for tests"
          ls -lh "$HOME/.ollama" || echo "Warning: .ollama directory not found"
        else
          echo "Model cache miss - tests will pull models on first run"
        fi
      env:
        STEPS_CACHE_OLLAMA_MODELS_OUTPUTS_CACHE_HIT: ${{ steps.cache-ollama-models.outputs.cache-hit }}
