#!/usr/bin/env bash
# Generate version.ts with git information

GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_DESCRIBE=$(git describe --tags --always --dirty 2>/dev/null || echo "unknown")
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# If the build runs in a dirty git checkout, `git describe --dirty` includes "-dirty".
# This extra output helps debug CI/release builds that end up stamped as dirty.
if git rev-parse --is-inside-work-tree >/dev/null 2>&1 && git rev-parse --verify HEAD >/dev/null 2>&1; then
  if ! git diff-index --quiet HEAD -- 2>/dev/null; then
    echo "⚠️  Git checkout is dirty; version will be stamped with '-dirty'."
    echo "Tracked dirty files:"
    git diff-index --name-only HEAD -- | sed 's/^/  - /'
  fi
fi

cat >src/version.ts <<EOF
// This file is auto-generated by scripts/generate-version.sh
// Do not edit manually

export const VERSION = {
  git_commit: "${GIT_COMMIT}",
  git_describe: "${GIT_DESCRIBE}",
  buildTime: "${TIMESTAMP}",
};
EOF

echo "Generated version.ts: ${GIT_DESCRIBE} (${GIT_COMMIT}) at ${TIMESTAMP}"
